name: Steps Example
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maak directory
        run: mkdir testmachine
                
      - name: schrijf uname commando naar file 
        run: uname -a > testmachine/output.txt
        
                
      - name: verfification step
        run: cat testmachine/output.txt

                        
      - name: verfification step 2
        run: ls -alhR 
